### PR TITLE
Add Craft Payments

### PR DESCRIPTION
**Pull request by hsyyid**
Similar to how jobs can have specific blocks they get paid for breaking, this allows jobs to be paid for crafting specific items.

### CODE REVIEW

**Comment by Erigitic** [comment]
Awesome! Thanks so much!

**Comment by hsyyid** [comment]
@Erigitic Alright, all done.

**Comment by Erigitic** [comment]
Is this using Sponge Vanilla?

**Comment by hsyyid** [comment]
@Erigitic It depends on SpongeVanilla to get access to SpongeCommon. I had to use `SlotAdapter` which is in SpongeCommon. Shouldn't be an issue.

**Comment by Erigitic** [comment]
Ok no problem. I just have no experience with SpongeVanilla so I wanted to know what I need to look into. Thanks.

**Comment by Erigitic** [comment]
By the way, I reverted the commit as I was not able to get it to work 100%. I plan on adding this later on when the API is more fleshed out, especially since it looks as if there will be a much cleaner way of doing this in the future (Using the [CraftingOutput](https://jd.spongepowered.org/4.0.3/org/spongepowered/api/item/inventory/crafting/CraftingOutput.html) and [CraftingInventory](https://jd.spongepowered.org/4.0.3/org/spongepowered/api/item/inventory/crafting/CraftingInventory.html) classes). There is even a chance a CraftItemEvent will be added with this [PR](https://github.com/SpongePowered/SpongeAPI/pull/1098).

**Comment by hsyyid** [comment]
@Erigitic What do you mean you were not able to get it to work 100%?

**Comment by Erigitic** [comment]
@hsyyid When taking the item out of the output slot it would only give me the exp/money for the final item/stack. For example, when making stone slabs, if I had enough stone in the crafting grid to make two stacks of 6 slabs, it did not give me anything for taking the first stack out.

**Comment by Erigitic** [comment]
@hsyyid Does it do the same for you or is it only happening on my end?

**Comment by hsyyid** [comment]
@Erigitic What happens if you shift-click

**Comment by Erigitic** [comment]
@hsyyid Testing now.

**Comment by Erigitic** [comment]
@hsyyid It still seems like it is only counting one of the stacks.

**Comment by hsyyid** [comment]
@Erigitic Alright, I'll try fixing it here in a bit.

**Comment by JonathanxD** [comment]
Why not add dependency of [SpongeCommon](https://github.com/SpongePowered/SpongeCommon) instead of [SpongeVanilla](https://github.com/SpongePowered/SpongeVanilla)?

**Comment by MarkL4YG** [comment]
Yep, this way it should work with Vanilla and Forge

**Pull request merged**
