### PR TITLE
Fix Missing job requirement check on job signs

### PR DESCRIPTION
**Pull request by MarkL4YG**
This will add code to the ``JobManager`` to make the interaction with job signs respect the defined job requirements.  
Additionally I went ahead and updated the German localization.  

I would like to ask @pigneedle to test this PR to see if their issue has been fixed.

---
Fixes: #273

### CODE REVIEW

**Comment by pigneedle** [comment]
I get a message that there is no message for failing to meet the requirements, but it seems to at least be checking now.

Error message when I use a job sign that I don't meet the level requirement for:
Message not found (en): jobs.unmet.level

**Comment by MarkL4YG** [comment]
Did you delete/rename your messages file so it is replaced by the updated one?

**Comment by pigneedle** [comment]
I didn't. I realized that just after I posted my comment. I'm loading it up now to verify it works. I expect it will since it was just calling a missing string. I'll post after I run it.

**Comment by pigneedle** [comment]
I now receive a different error. When I use a sign, instead of the previous error, I now get:
`Error occurred while executing command: null`

This is on a fresh server running:
Minecraft 1.12.2
Forge 14.23.3.2655
SpongeForge 1.12.2-2655-7.1.0

I don't think this error is related to this issue.

**Comment by MarkL4YG** [comment]
@pigneedle Should be fixed. Please re-do your messages file once again.

**Comment by pigneedle** [comment]
Job requirements seem to be working now after some testing.

**Pull request merged**
