### PR TITLE
[WIP] Add Craft Payments

### PR DESCRIPTION
**Pull request by hsyyid**
Similar to how jobs can have specific blocks they get paid for breaking, this allows jobs to be paid for crafting specific items.

### CODE REVIEW

**Comment by Erigitic** [comment]
I will look through this over the next couple of days. Thanks for the help!

**Comment by hsyyid** [comment]
@Erigitic It's not ready yet, there's an issue with detecting the crafting properly, but once that's sorted it should be good.

**Comment by Erigitic** [comment]
Sounds good. I will look into it and see if I can come up with something.

**Comment by Erigitic** [comment]
Would it be possible for you to create a new pull request and target the develop branch? I want to avoid changing the code in the master branch just in case something ends up breaking. Thanks.

**Pull request closed without merging**
