### PR TITLE
Fixed GitHub Repo and Updated to SpongeForge 833+

### PR DESCRIPTION
**Pull request by hsyyid**
I updated to use the new way of getting builders, as well as fixed up your repository so it follows normal conventions.

### CODE REVIEW

**Comment by Erigitic** [comment]
Awesome! Will look this over and get it added. Thanks for the help.

**Comment by hsyyid** [comment]
@Erigitic Of course, :smile:

**Comment by Erigitic** [comment]
Done

**Comment by hsyyid** [comment]
Why didn't you just merge the PR?

**Comment by Erigitic** [comment]
I like to test out the code to make sure everything works out as planned before pushing it to GitHub. As far as I know, when merging a PR, I cannot do this.

**Comment by hsyyid** [comment]
Ah. Well, you know you can merge the PR, test to verify it works, and if not, undo the merge. Cheers!

**Comment by Erigitic** [comment]
Did not know that. I am a novice GitHub user so I am still in the process of understanding everything. Will keep this in mind for the next time. Sorry about the confusion and thanks again for the help.

**Pull request closed without merging**
