### PR TITLE
[WIP] Job update candidate

### PR DESCRIPTION
**Pull request by MarkL4YG**
Hey @Erigitic ,
As I had a little time today I decided to think a little about that job update that's queued.

So, here's what I came up with:

* New config "jobSets"
  Definitions for job sets where each set can have all events covered.
For example: ``minerSet`` can have a node ``break``, a node ``place`` and so on.
Under each node one can add target IDs like ``minecraft:stone`` which each have (currently) 2 sub nodes, ``expGain`` and ``moneyGain`` to define the loan.

* Job+JobSet+ActionReward instances
  I've defined classes for each causing handling jobs (read only) not to require the usage of ConfigurationNodes anymore. Directly working with the config instance felt to painful for me.

* Multiple JobSets for jobs
  Job nodes are now located under the ``jobs`` node in the config to separate things more clearly and due to me using ``ChildrenMap``s on the nodes (Meaning to prevent random other nodes to become jobs). Also each job now has a list ``sets`` which determines which sets TE should look through when a player triggers one of the payable(?) events.

* ``JobBasedRequirement``s
  ... is the name I came up with. A requirement basically defines a permission and/or a job and a corresponding level that have to be met in order to fullfill the requirement. Currently this is implemented in ``SetJobCommand`` where one can now define that a player wanting to enter (e.g.) the ``miner2`` job needs to be at least level ``4`` in the job ``miner``

* ``job info`` command has a new parameter + response
  I added ``jobName`` as an argument so one can view job information of other jobs and refactored the response a little. Not quite satisfied with it though. I'm thinking of adding an item overlay when hovered for example, so it's a bit more decorated.

It's been quite a little work, so please excuse me if I left something out. Just ask and I'll explain if needed.
As always: I hope this is useful for you :)
(I also don't get why I cant request to push this into a new branch in your repository... )

Initial commit message
---
* Add TEJobSet
* Add TEJob
* Add TEActionReward
  - Both are cached, actions no longer 100% directly on config (currently all r.o. though)
* Port Default Jobs to new system
* Jobs can now have requirements (permission and/or a specific level in a specific job)
* Change layout of ``job info`` command (+ add [jobName] as parameter)
* Change level+exp node to ``.jobstats.<jobname>.~``
* Change job names to be lowercase only
* Optimize imports run

Tested on
---
* SpongeAPI 5.1.0-SNAPSHOT
* SpongeVanilla (latest commit in branch [``stable-5``](https://github.com/SpongePowered/SpongeVanilla/tree/stable-5) (corresponding SV version not available))
* SpongeForge (latest commit in branch [``stable-5``](https://github.com/SpongePowered/SpongeForge/tree/stable-5) (corresponding SV version not available))

Linked issues
---
* #66
* #107 
* #112
* #115
* #125 Solved for JobSetCommand
* #133

Missing changes
---
* #44 
* #133

### CODE REVIEW

**Comment by MarkL4YG** [comment]
And since @yololetsplay requested it: I've created a dev release to mess with:
https://github.com/MarkL4YG/TotalEconomy/releases/tag/v1.5.3-JobPreview
@Erigitic If you don't want me to, I can take it down of course.

**Comment by yololetsplay** [comment]
This is great! I will give it a try ;] I it's not much time for you, I would welcome this kind of releases in future ;]

Greetz,
Hannes

**Comment by MarkL4YG** [comment]
@yololetsplay thanks. Make sure to report any issues you encounter in [my fork](https://github.com/MarkL4YG/TotalEconomy/issues) as long as this isn't closed since @Erigitic can't fix what I broke ^^
And:
Well, it of course is a little time consuming indeed. I'm preparing for my exams at the end of spring and I'm going to study beginning in October ':)
There may be times of me doing this kind of things but certainly not each weekend ^^

**Comment by Erigitic** [comment]
I have not thoroughly looked through this yet as I have been busy moving back to school, but from what I saw it is looking great. Regarding dev releases, what I can do is set up Travis CI to automatically create dev releases whenever a commit is made. This probably won't happen for a while though. Also, thanks for creating the dev release @MarkL4YG.

**Few questions:**
Does this work on Sponge Forge? If not, would it be best to use Sponge Vanilla from here on out, which is what I think you are using here? If we did use Sponge Vanilla, what effect would this have on servers that are using Sponge Forge? Lastly, do custom jobs still work?

I will test this out on my end and get it merged into what will most likely become v1.6.0. As always, thanks for the great work @MarkL4YG.

**Comment by MarkL4YG** [comment]
@Erigitic I use SpongeVanilla because it compiles and starts faster ':D
In theory this should work just aswell in SpongeForge. (API implementations are the same on both).
I expect difficulties when you/we start to touch meta-data though. (I didn't for now)

If you mean adding any jobs to the config: Yes, one can add any lowercase job node to the "jobs" node. In order for it to be enabled it needs to have at least a "salary"(BigInteger) and a "sets"(List of String) field.
For it to be usefull the "sets" field should contain defined sets (see the sets config).
As before, the plugin generates an example config when none exists. :)

**Comment by MarkL4YG** [comment]
Just as a side note: I'm considering to suggest renaming the ``TEJobs`` class to something like ``TEJobManager`` or so. Just to stop my IDE or me from confusing it with ``TEJob`` ^^

**Comment by Erigitic** [comment]
@MarkL4YG I agree with the name change. Makes more sense calling it TEJobManager.

**Comment by MarkL4YG** [comment]
@Erigitic then I'll just include that in this PR.

**Pull request merged**
