### PR TITLE
Fixed onSignInteract exceptions | Fixed JobSigns

### LINKED ISSUE #53: Possibile Jobs Issue
`

[21:40:27] [Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Primary$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@17579c3e
java.util.NoSuchElementException: No value present

at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_45-internal]

at com.erigitic.jobs.TEJobs.onSignInteract(TEJobs.java:331) ~[TEJobs.class:?]

at org.spongepowered.common.event.listener.InteractBlockEventListener_TEJobs_onSignInteract74.handle(Unknown Source) ~[?:?]

at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8.9-1808-4.1.0-BETA-1254]

at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:238) [SpongeModEventManager.class:1.8.9-1808-4.1.0-BETA-1254]

at org.spongepowered.mod.event.SpongeModEventManager.postBulk(SpongeModEventManager.java:225) [SpongeModEventManager.class:1.8.9-1808-4.1.0-BETA-1254]

at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:264) [SpongeModEventManager.class:1.8.9-1808-4.1.0-BETA-1254]

at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:250) [SpongeModEventManager.class:1.8.9-1808-4.1.0-BETA-1254]

at net.minecraft.server.MinecraftServer.handler$onServerTick$0(MinecraftServer.java:1047) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:650) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]

-------------------------------------------------------------------------------------------------------------------------------

[21:43:12] [Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Secondary$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@17579c3e
java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_45-internal]
at com.erigitic.jobs.TEJobs.onSignInteract(TEJobs.java:331) ~[TEJobs.class:?]
at org.spongepowered.common.event.listener.InteractBlockEventListener_TEJobs_onSignInteract74.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8.9-1808-4.1.0-BETA-1254]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:238) [SpongeModEventManager.class:1.8.9-1808-4.1.0-BETA-1254]
at org.spongepowered.mod.event.SpongeModEventManager.postBulk(SpongeModEventManager.java:225) [SpongeModEventManager.class:1.8.9-1808-4.1.0-BETA-1254]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:264) [SpongeModEventManager.class:1.8.9-1808-4.1.0-BETA-1254]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:250) [SpongeModEventManager.class:1.8.9-1808-4.1.0-BETA-1254]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:128) [SpongeImpl.class:1.8.9-1808-4.1.0-BETA-1254]
at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:606) [SpongeCommonEventFactory.class:1.8.9-1808-4.1.0-BETA-1254]
at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:601) [SpongeCommonEventFactory.class:1.8.9-1808-4.1.0-BETA-1254]
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:521) [lm.class:?]
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) [ja.class:?]
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) [ja.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:106) [PacketUtil.class:1.8.9-1808-4.1.0-BETA-1254]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:51) [fh$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]`

### LINKED ISSUE #54: Created [TEJobs] sign goes blank
Reproduce:

1. Place a sign
2. First line "[TEJobs]"
3. Other lines don't matter
4. Click "done"

Sign has cleared first 2 if not all lines.

### PR DESCRIPTION
**Pull request by MarkL4YG**
- Resolves #53
- Resolves #54

### CODE REVIEW

**Comment by MarkL4YG** [comment]
Side fact:

I just noticed that your initial commit was on my 17. birthday :+1:

**Comment by Erigitic** [comment]
Thanks for the help. I can't test this now but I will later today.

**Comment by MarkL4YG** [comment]
You're welcome, needed to do these anyway because we decided to use your plugin for our servers ^^

**Comment by Erigitic** [comment]
Sorry for waiting so long to merge this but I am currently working on this now. Thanks again for the help. I really appreciate it.

**Comment by Erigitic** [comment]
Going to merge this into a new branch to avoid pushing directly to the master branch.

**Comment by Erigitic** [comment]
I reverted because I am going to split these up as I do not want to keep temporary code in the SetBalanceCommand file. Going to figure out a more permanent solution to this. The other file looks great and I am testing it now. Thanks.

**Pull request merged**
