### PR TITLE
[WIP] Add trait-support to the Jobs feature

### LINKED ISSUE #193: Jobs not working correctly
Miner, Lumberjack, and Farmer are all giving me issues. It seems like the break command isn't working correctly
The only thing that works is the breaking of the wheat for the Farmer job, I've deleted the jobs and jobsets configs multiple times...

### LINKED ISSUE #197: [Jobs] Meta-ID support (sort of)
Currently blocks are only identified by their name. But some(tm) modifications additionally use meta-ids or ``BlockProperty``s to identify different blocks with the same dictionary name. This makes TE see (e.g.) tin and copper like they're the same ore since both can have the ID/Name ``<modid>:ore``.
Additionally some debug tool for admins to get such information would be nice.

I've already started working on a solution for this and will submit a PR shortly.

This will resolve / See discussion: #193

### PR DESCRIPTION
**Pull request by MarkL4YG**
Hello there,

As discussed in #193 (Tracking issue #197) this adds trait support to the actions defined in JobSets.  

Breaking changes
---
JobSets general appearance changed as money and exp now use ``Double`` and ``Integer`` as type instead of string.  
Example:
```´hocon
sets {
    crops {
        break {
            "minecraft:brown_mushroom" {
                exp=8
                money=5.00
            }
        }
    }
}
```
Additionally I've prepared to change ``growthTrait`` to ``growth-trait`` so it matches the style of the main configuration. However both the new and old one currently work.
```hocon
sets {
    crops {
        break {
            "minecraft:brown_mushroom" {
                exp=8
                money=5.00
            }
            "minecraft:wheat" {
                exp=25
                growth-trait=age
                money=50.00
            }
        }
    }
}
```

Additions
---
If enabled the Actions to closer analyze the block type by also examining one block trait.  
Codewise this is a bigger change as now ``TEAction`` and ``TEActionReward`` are two different things while in the config the reward declaration just shifts inwards:  
The property ``id-trait`` now determines the trait ``name``(!) the action examines while a node with the traits name holds possible values and what their salary would be.  
Example:
```hocon
sets {
    crops {
        break {
            "minecraft:brown_mushroom" {
                exp=8
                money=5.00
            }
            "minecraft:wheat" {
                exp=25
                growth-trait=age
                money=50.00
            }
            "techreborn:techreborn.ore": {
                id-trait="type"
                type {
                  bauxite {
                    exp=1
                    money=50.00
                  }
                }
            }
        }
    }
}
```
Side-Note: ID-Traits won't stop Growth-Traits from working. If you specify growth in the root node where you normally would that growth modifier is applied after the id-trait has been checked.  

Commands
---
I also added a parameter to ``job toggle`` named ``option`` which takes either of ``{"block-break-info", "block-place-info", "entity-kill-info", "entity-fish-info"}`` values.  
Using these options the account manager toggles the option between ``"0"`` and ``"1"`` which in turn is read by the ``JobManager`` and basically tells him to send additional information to the client upon the caught events.  
This for example will list all the block traits and their values when one places or breaks a block.

Issues
---
* Closes #193
* Fixes #197

Tested with
---
* SpongeForge (stable-5 branch)
* Modification "TechReborn"

The last hours were quite stressful so in case I forgot anything: just ask ^^.
Also: I don't know why GH shows conflicts on the main repo develop branch but not on my fork which should have the same state.

Preview
---
This mainly is for @TheAJArts for testing purposes:
https://github.com/MarkL4YG/TotalEconomy/releases/tag/v1.7.1-SNAPSHOT

### CODE REVIEW

**Comment by MarkL4YG** [comment]
I realized that a lot of commits from the last PR are included in here... @Erigitic if you want me to redo the PR I'd do that but that won't be ahead of Sunday I suppose.

**Comment by TheAJArts** [comment]
I'll give it a test run when I get back to my desk!

**Comment by TheAJArts** [comment]
It works! I also went ahead and threw in the mod "Mekanism" and found the page containing the names of the ores:
[https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/block/states/BlockStateOre.java](url)
And tried this:
`            "mekanism:OreBlock" {
                id-trait="type"
                type {
                  TIN: {
                    exp=1
                    money=50.00
                  }
                }
            }`

Which also works flawlessly!

**Comment by MarkL4YG** [comment]
Resubmitted - closed

**Pull request closed without merging**
